name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.2.0
        
      - name: Unit testing of module with Terratest
        run: |
          cd tests
          go mod init azuresql
          go get github.com/gruntwork-io/terratest/modules/terraform
          go test -timeout 60m
